<?php
require_once(__DIR__ . '/../db_connect.php');

if (!isset($_POST['sales_no_checkbox'])) {
    echo "2";
    exit;
}

$sales_list = $_POST['sales_no_checkbox'];

$total_balance = 0;
$total_amount = 0;
$total_other = 0;

// Get customer info if available
$customer_name = "";
if (isset($_POST['cust_id'])) {
    $cust_id = $_POST['cust_id'];
    $cust_query = $db->query("SELECT * FROM tbl_customer WHERE cust_id='$cust_id'");
    if ($cust_row = $cust_query->fetch_assoc()) {
        $customer_name = $cust_row['name'];
    }
}
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Statement of Account</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            max-height: 60px;
        }

        .header h1 {
            margin: 5px 0 0 0;
            font-size: 24px;
        }

        .header h3 {
            margin: 0;
            font-size: 16px;
            font-weight: normal;
        }

        .customer-info {
            margin: 20px 0;
        }

        .customer-info p {
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table th,
        table td {
            border: 1px solid #333;
            padding: 8px 10px;
            text-align: left;
        }

        table th {
            background-color: #26a69a;
            color: white;
        }

        table tfoot th {
            background-color: #f0f0f0;
            text-align: right;
        }

        table tfoot td {
            font-weight: bold;
        }

        .text-right {
            text-align: right;
        }

        .signatures {
            width: 100%;
            margin-top: 50px;
        }

        .signatures td {
            vertical-align: top;
            padding-top: 50px;
            font-size: 14px;
        }

        .sign-line {
            border-top: 1px solid #333;
            width: 80%;
            display: inline-block;
            margin-top: 10px;
        }
    </style>
</head>

<body>

    <div class="header">
        <img src="../images/main_logo.jpg" alt="Cooperative Logo">
        <h1>Opol Community College <br> Employees Credit Cooperative</h1>
        <h3>Statement of Account</h3>
        <p>Date: <?= date("F d, Y") ?></p>
    </div>

    <div class="customer-info">
        <p><strong>Customer:</strong> <?= htmlspecialchars($customer_name) ?></p>
        <p><strong>Generated By:</strong> <?= $_SESSION['username'] ?? 'System' ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Bill No.</th>
                <th class="text-right">Amount</th>
                <th class="text-right">Other Amount</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($sales_list as $sales_no) {
                $query = $db->query("SELECT * FROM tbl_sales WHERE sales_no='$sales_no'");
                while ($row = $query->fetch_assoc()) {
                    $sales_id = str_pad($row['sales_id'], 8, "0", STR_PAD_LEFT);
                    $total_amount += $row['total_amount'];
                    $total_other += $row['other_amount'];
                    $total_balance += $row['balance'];
            ?>
                    <tr>
                        <td><?= date("F d, Y", strtotime($row['sales_date'])) ?></td>
                        <td><?= $sales_id ?></td>
                        <td class="text-right"><?= number_format($row['total_amount'], 2) ?></td>
                        <td class="text-right"><?= number_format($row['other_amount'], 2) ?></td>
                        <td class="text-right"><?= number_format($row['balance'], 2) ?></td>
                    </tr>
            <?php
                }
            }
            ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2" class="text-right">TOTAL:</th>
                <th class="text-right"><?= number_format($total_amount, 2) ?></th>
                <th class="text-right"><?= number_format($total_other, 2) ?></th>
                <th class="text-right"><?= number_format($total_balance, 2) ?></th>
            </tr>
        </tfoot>
    </table>

    <table class="signatures">
        <tr>
            <td>
                Prepared by:<br>
                <div class="sign-line"></div>
            </td>
            <td align="right">
                Received by:<br>
                <div class="sign-line"></div>
            </td>
        </tr>
    </table>

</body>

</html>